### ISSUE TITLE
CoreAnimatedPages.onTransitionEnd broken in chromium

### ISSUE THREAD

**Issue by kornel661** [dart-lang/core-elements#203]
My code:
```dart
_coreAnimatedPages.onTransitionEnd.listen((_) {
  print('message');
});
```
works neither in Chromium 41.0.2272.76 (64-bit) nor Chrome 42.0.2311.50 beta (64-bit) under Linux (I used `pub serve`, there's no message in the console, the event seems not to be fired at all). Animations and everything else work as expected.

The same code works in Dartium 39.0.2171.99 (64-bit) (executed as dart) and in Firefox 31.5.0.

What is more,
```dart
_coreAnimatedPages.on['transitionend'].listen(...)
```
works in Firefox only (I discovered it while debugging the issue).

I'm using
```yaml
dependencies:
  browser: '^0.10.0+2'
  core_elements: '^0.6.1+2'
  paper_elements: '^0.6.2+2'
  polymer: '^0.16.0+6'
```
