### ISSUE TITLE
Importing core-icons causes HTTP server to become unresponsive

### ISSUE THREAD

**Issue by davenotik** [dart-lang/core-elements#55]
Pseudo-repro:

Include these in your .html:

```
<link href="packages/core_elements/core_icons.html" rel="import">
<link href="packages/paper_elements/paper_fab.html" rel="import">
```

Use a simple HTTP server to serve the page. I've tried using Node's `http-server`, `python SimpleHTTPServer` and WebStorm's built-in server.

When you hit your page with the above packages, it stalls, waits forever. Remove the first line, the core-icons package, and it works again.

Tried in Dartium and other browsers, so it's not a browser thing.

```
paper_elements:
    description: paper_elements
    source: hosted
    version: "0.0.1"

core_elements:
    description: core_elements
    source: hosted
    version: "0.0.6"
```
